# .github/workflows/ansible-lint.yml
name: Lint and Test Ansible Role
run-name: Lint and test role on code of user @${{ github.actor }}
on:
  workflow_dispatch:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

defaults:
  run:
    working-directory: 'msterhuj.bind9'

jobs:
  lint:
    name: Ansible Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'msterhuj.bind9'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tox
        run: pip install tox

      - name: Lint code.
        run: |
          tox -e lint

  molecule:
    name: Molecule (${{ matrix.scenario }}) on ${{ matrix.distro }}
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distro:
          - ubuntu2204
          - ubuntu2404
          - debian12
          - debian11
        scenario:
          - default
    steps:
      - uses: actions/checkout@v4
        with:
          path: 'msterhuj.bind9'

      - name: Set up Python 3.
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install tox
        run: pip install tox

      - name: Run Molecule via tox
        run: tox -e molecule -- --scenario-name ${{ matrix.scenario }}
        env:
          IMAGE: geerlingguy/docker-${{ matrix.distro }}-ansible
